apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:      
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react-app
          image: chinmayyajaman/react-app:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: react
  ports:
    - name: http
      port: 30010
      targetPort: 3000
      nodePort: 31111
